# Generated by Django 2.2.2 on 2019-06-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scientist',
            old_name='becal',
            new_name='has_becal_scholarship',
        ),
        migrations.AddField(
            model_name='scientist',
            name='aproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scientist',
            name='institutional_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='position',
            field=models.CharField(choices=[('master_academico', 'Estudiante de Máster Académico'), ('doctorando', 'Estudiante de Doctorado'), ('postdoc', 'Post-doc'), ('profesor', 'Profesor'), ('otro', 'Otro')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='scientific_area',
            field=models.CharField(choices=[('agricultura', 'Agricultura'), ('artes', 'Artes'), ('biologia', 'Biología'), ('biotecnologia_agricola', 'Biotecnología Agrícola'), ('biotecnologia_ambiente', 'Biotecnología del Ambiente'), ('biotecnologia_industrial', 'Biotecnología Industrial'), ('biotecnologia_medica', 'Biotecnología Médica'), ('educacion', 'Ciencias de la Educación'), ('ciencias_politicas', 'Ciencias Políticas'), ('ciencias_salud', 'Ciencias de la Salud'), ('comunicaciones', 'Comunicaciones'), ('economia', 'Economía'), ('filosofia', 'Filosofía'), ('fisica', 'Fisica'), ('ganaderia', 'Ganadería'), ('geografia', 'Geografía'), ('historia', 'Historia y Arqueología'), ('informatica', 'Informática'), ('ing_ambiente', 'Ingenieria del Ambiente'), ('ing_civil', 'Ingenieria Civil'), ('ing_electronica', 'Ingenieria Electrónica'), ('ing_materiales', 'Ingenieria de Materiales'), ('ing_mecanica', 'Ingenieria Mecánica'), ('ing_quimica', 'Ingenieria Química'), ('lengua_literatura', 'Lengua y Literatura'), ('leyes', 'Leyes'), ('matematica', 'Matematica'), ('medician_basica', 'Medicina Básica'), ('medician_clinica', 'Medicina Clinica'), ('nano_tecnologia', 'Nano-Tecnología'), ('psicologia', 'Psicología'), ('quimica', 'Quimica'), ('religion', 'Religión'), ('sociologia', 'Sociología'), ('veterinara', 'Veterinaria'), ('otro', 'Otro')], default='', max_length=100),
        ),
    ]
