# Generated by Django 2.2.2 on 2019-06-30 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190630_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scientist',
            old_name='aproved',
            new_name='approved',
        ),
    ]
