# Generated by Django 2.2.2 on 2019-07-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190630_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
