# Generated by Django 2.2.2 on 2019-08-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_scientist_communication_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientist',
            name='facebook_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scientist',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='communication_channel',
            field=models.CharField(choices=[('whatsapp', 'Grupo de Whatsapp'), ('slack', 'Espacio de Trabajo en Slack'), ('telegram', 'Grupo de Telegram'), ('lista_correo', 'Lista de Correo'), ('facebook', 'Grupo de Facebook')], default='', max_length=100),
        ),
    ]
