# Generated by Django 2.2.5 on 2019-09-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190822_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientist',
            name='personal_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
