# Generated by Django 2.2.5 on 2019-09-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_scientist_personal_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scientist',
            name='orcid',
        ),
        migrations.AddField(
            model_name='scientist',
            name='orcid_profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
