# Generated by Django 2.2.5 on 2019-10-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191013_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientist',
            name='end_becal_scholarship',
            field=models.DateField(blank=True, null=True),
        ),
    ]
