# Generated by Django 2.2.5 on 2019-10-20 20:52

import app.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_scientist_end_becal_scholarship'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='edited_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='institution',
            name='edited_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='scientist',
            name='academia_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scientist',
            name='ci',
            field=models.CharField(default='000000', max_length=100),
        ),
        migrations.AddField(
            model_name='scientist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='scientist',
            name='edited_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='scientist',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scientist',
            name='researchgate_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scientist',
            name='slug',
            field=models.SlugField(default="-1", max_length=40),
        ),
    ]
