# Generated by Django 2.2.5 on 2019-10-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20191020_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientist',
            name='ci',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='slug',
            field=models.SlugField(max_length=40, unique=True),
        ),
    ]
