# Generated by Django 2.2.5 on 2019-10-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20191021_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientist',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True),
        ),
    ]
