# Generated by Django 2.2.5 on 2019-12-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20191024_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientist',
            name='first_category_scientific_area',
            field=models.CharField(choices=[('ciencias_naturales', 'Ciencias Naturales'), ('ingenieria', 'Ingeniería y Tecnología'), ('ciencias_medicas', 'Ciencias Médicas y de la Salud'), ('ciencias_agricolas', 'Ciencias Agrícolas y Veterinarias'), ('ciencias_sociales', 'Ciencias Sociales'), ('humanidades_artes', 'Humanidades y Artes'), ('', '')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='communication_channel',
            field=models.CharField(choices=[('whatsapp', 'Grupo de Whatsapp'), ('slack', 'Espacio de Trabajo en Slack'), ('telegram', 'Grupo de Telegram'), ('lista_correo', 'Lista de Correo'), ('facebook', 'Grupo de Facebook'), ('', '')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='scientific_area',
            field=models.CharField(choices=[('agricultura', 'Agricultura, Silvicultura y Pesca'), ('arte', 'Artes'), ('biologia', 'Biología'), ('biotecnologia_agricola', 'Biotecnología Agrícola'), ('biotecnologia_ambiente', 'Biotecnología Ambiental'), ('biotecnologia_industrial', 'Biotecnología Industrial'), ('biotecnologia_medica', 'Biotecnología Médica'), ('ciencias_animal', 'Ciencia Animal y de los Lácteos'), ('ciencias_informacion', 'Ciencias de la Información y Comunicación'), ('ciencias_politicas', 'Ciencias Políticas'), ('ciencias_salud', 'Ciencias de la Salud'), ('ciencias_ambiente', 'Ciencias de la Tierra y relacionadas al Medio Ambiente'), ('comunicaciones', 'Medios de Comunicación'), ('leyes', 'Derecho'), ('economia', 'Economía y Comercio'), ('educacion', 'Educación'), ('filosofia', 'Filosofía, Ética y Religión'), ('fisica', 'Fisica'), ('geografia', 'Geografía Social y Económica'), ('historia', 'Historia y Arqueología'), ('informatica', 'Informática'), ('ing_ambiente', 'Ingenieria Ambiental'), ('ing_civil', 'Ingenieria Civil'), ('ing_electronica', 'Ingenieria Eléctrica y Electrónica'), ('ing_materiales', 'Ingenieria de Materiales'), ('ing_mecanica', 'Ingenieria Mecánica'), ('ing_medica', 'Ingenieria Médica'), ('ing_quimica', 'Ingenieria Química'), ('lengua_literatura', 'Lengua y Literatura'), ('matematica', 'Matemática'), ('medicina_basica', 'Medicina Básica'), ('medicina_clinica', 'Medicina Clínica'), ('nano_tecnologia', 'Nanotecnología'), ('psicologia', 'Psicología y ciencias cognitivas'), ('quimica', 'Quimica'), ('sociologia', 'Sociología'), ('veterinaria', 'Veterinaria'), ('otras_agricola', 'Otras ciencias agricolas'), ('otras_humanas', 'Otras ciencias humanas'), ('otras_naturales', 'Otras ciencias naturales'), ('otras_medica', 'Otras ciencias médicas'), ('otras_ingenierias', 'Otras ingenierías y tecnologías'), ('otras_sociales', 'Otras ciencias sociales')], default='', max_length=100),
        ),
    ]
