# Generated by Django 2.2.5 on 2019-12-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20191206_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientist',
            name='rough_age',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='communication_channel',
            field=models.CharField(choices=[('whatsapp', 'Grupo de Whatsapp'), ('slack', 'Espacio de Trabajo en Slack'), ('telegram', 'Grupo de Telegram'), ('lista_correo', 'Lista de Correo'), ('facebook', 'Grupo de Facebook'), ('otro', '')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='first_category_scientific_area',
            field=models.CharField(choices=[('ciencias_naturales', 'Ciencias Naturales'), ('ingenieria', 'Ingeniería y Tecnología'), ('ciencias_medicas', 'Ciencias Médicas y de la Salud'), ('ciencias_agricolas', 'Ciencias Agrícolas y Veterinarias'), ('ciencias_sociales', 'Ciencias Sociales'), ('humanidades_artes', 'Humanidades y Artes'), ('', '')], default='', editable=False, max_length=100),
        ),
    ]
