# Generated by Django 2.2.8 on 2020-01-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20191206_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientist',
            name='ci',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='scientific_area',
            field=models.CharField(choices=[('agricultura', 'Agricultura, Silvicultura y Pesca'), ('arte', 'Artes'), ('biologia', 'Biología'), ('biotecnologia_agricola', 'Biotecnología Agrícola'), ('biotecnologia_ambiente', 'Biotecnología Ambiental'), ('biotecnologia_industrial', 'Biotecnología Industrial'), ('biotecnologia_medica', 'Biotecnología Médica'), ('ciencias_animal', 'Ciencia Animal y de los Lácteos'), ('ciencias_informacion', 'Ciencias de la Información y Comunicación'), ('ciencias_politicas', 'Ciencias Políticas'), ('ciencias_salud', 'Ciencias de la Salud'), ('ciencias_ambiente', 'Ciencias de la Tierra y relacionadas al Medio Ambiente'), ('comunicaciones', 'Medios de Comunicación'), ('leyes', 'Derecho'), ('economia', 'Economía y Comercio'), ('educacion', 'Educación'), ('filosofia', 'Filosofía, Ética y Religión'), ('fisica', 'Fisica'), ('geografia', 'Geografía Social y Económica'), ('historia', 'Historia y Arqueología'), ('informatica', 'Informática'), ('ing_ambiente', 'Ingenieria Ambiental'), ('ing_civil', 'Ingenieria Civil'), ('ing_electronica', 'Ingenieria Eléctrica y Electrónica'), ('ing_materiales', 'Ingenieria de Materiales'), ('ing_mecanica', 'Ingenieria Mecánica'), ('ing_medica', 'Ingenieria Médica'), ('ing_quimica', 'Ingenieria Química'), ('lengua_literatura', 'Lengua y Literatura'), ('matematica', 'Matemática'), ('medicina_basica', 'Medicina Básica'), ('medicina_clinica', 'Medicina Clínica'), ('nano_tecnologia', 'Nanotecnología'), ('psicologia', 'Psicología y ciencias cognitivas'), ('quimica', 'Quimica'), ('sociologia', 'Sociología'), ('veterinaria', 'Veterinaria'), ('otras_agricola', 'Ciencias agricolas'), ('otras_humanas', 'Ciencias humanas'), ('otras_naturales', 'Ciencias naturales'), ('otras_medica', 'Ciencias médicas'), ('otras_ingenierias', 'Ingenierías y tecnologías'), ('otras_sociales', 'Ciencias sociales')], default='', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='scientist',
            unique_together={('email', 'ci')},
        ),
    ]
