# Generated by Django 2.2.10 on 2021-05-20 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200110_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scientist',
            old_name='end_becal_scholarship',
            new_name='end_abroad_period',
        ),
    ]
