# Generated by Django 2.2.10 on 2021-06-17 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210520_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationUpdateScientist',
            fields=[
                ('it_has_been_notified', models.BooleanField(default=False)),
                ('scientist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Scientist')),
            ],
        ),
    ]
