# Generated by Django 2.2.10 on 2021-06-18 18:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210520_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationScientist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('type', models.CharField(choices=[('ABROAD_PERIOD_EXPIRATION', 'FECHA DE RETORNO EXPIRADA'), ('otro', '')], default='', max_length=100)),
                ('scientist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Scientist')),
            ],
        ),
    ]
