# Generated by Django 2.2.10 on 2021-06-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210520_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientist',
            name='notify_end_abroad_period_has_ended',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
