SEX = (
    ('femenino', 'Femenino'),
    ('masculino', 'Masculino'),
    ('otro', 'Otro'),
)

SCIENTIFIC_AREA = (
    ('administracion', 'Administración'),
    ('agricultura', 'Agricultura'),
    ('antropoligia', 'Antropoligía'),
    ('artes', 'Artes'),
    ('arquitectura', 'Arquitectura'),
    ('astronomia', 'Astronomía'),
    ('biologia', 'Biología'),
    ('bioquimica', 'Bioquímica'),
    ('biotecnologia_agricola', 'Biotecnología Agrícola'),
    ('biotecnologia_ambiente', 'Biotecnología del Ambiente'),
    ('biotecnologia_industrial', 'Biotecnología Industrial'),
    ('biotecnologia_medica', 'Biotecnología Médica'),
    ('botanica', 'Botánica'),
    ('educacion', 'Ciencias de la Educación'),
    ('ciencias_ambiente', 'Ciencias del Medio Ambiente'),
    ('ciencias_politicas', 'Ciencias Políticas'),
    ('ciencias_sociales', 'Ciencias Sociales'),
    ('ciencias_salud', 'Ciencias de la Salud'),
    ('comunicaciones', 'Comunicaciones'),
    ('economia', 'Economía'),
    ('filosofia', 'Filosofía'),
    ('fisica', 'Fisica'),
    ('ganaderia', 'Ganadería'),
    ('geografia', 'Geografía'),
    ('historia', 'Historia y Arqueología'),
    ('informatica', 'Informática'),
    ('ing_ambiente', 'Ingenieria del Ambiente'),
    ('ing_civil', 'Ingenieria Civil'),
    ('ing_electronica', 'Ingenieria Electrónica'),
    ('ing_industrial', 'Ingenieria Industrial'),
    ('ing_materiales', 'Ingenieria de Materiales'),
    ('ing_mecanica', 'Ingenieria Mecánica'),
    ('ing_quimica', 'Ingenieria Química'),
    ('lengua_literatura', 'Lengua y Literatura'),
    ('leyes', 'Leyes'),
    ('matematica', 'Matemática'),
    ('medicina_basica', 'Medicina Básica'),
    ('medicina_clinica', 'Medicina Clínica'),
    ('nano_tecnologia', 'Nano-Tecnología'),
    ('psicologia', 'Psicología'),
    ('quimica', 'Quimica'),
    ('religion', 'Religión'),
    ('sociologia', 'Sociología'),
    ('veterinaria', 'Veterinaria'),
    ('otro', 'Otro'),
)

POSITION = (
    ('master_academico', 'Estudiante de Máster Académico'),
    ('doctorando', 'Estudiante de Doctorado'),
    ('postdoc', 'Post-doc'),
    ('profesor', 'Profesor'),
    ('otro', 'Otro'),
)

COMMUNICATION_CHANNELS = (
    ('whatsapp', 'Grupo de Whatsapp'),
    ('slack', 'Espacio de Trabajo en Slack'),
    ('telegram', 'Grupo de Telegram'),
    ('lista_correo', 'Lista de Correo'),
    ('facebook', 'Grupo de Facebook')
)